//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SmsText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SmsText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SmsText", typeof(SmsText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سپیتا.
        /// </summary>
        public static string Brand {
            get {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لینک سایت:.
        /// </summary>
        public static string DownloadLink {
            get {
                return ResourceManager.GetString("DownloadLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه عبور شما برابر است با.
        /// </summary>
        public static string FrogetPasswird_Part1 {
            get {
                return ResourceManager.GetString("FrogetPasswird_Part1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to با معرفی سپیتا به دوستانتون و انجام اولین سفارش آن ها 5000 تومان اعتبار رایگان هدیه بگیرید.
        /// </summary>
        public static string InviteOfferText {
            get {
                return ResourceManager.GetString("InviteOfferText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سلام دوستم. اگه تو هم خیلی سرت شلوغه که وقت نظافت منزل یا محل کارت یا حتی شستن ماشینت رو نداری یا دوس داری کسی تو کارات کمکت کنه کافیه بزنی رو لینک زیر و سپیتا رو دانلود کنی تا یه همیار با حال و کاربلد بیاد کارایی که داری رو انجام بده. راستی تخفیف دوس داری؟ کد معرف.
        /// </summary>
        public static string InviteText {
            get {
                return ResourceManager.GetString("InviteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رو بزن ۱۵۰۰۰ تومن اعتبار اولیه هدیه بگیر.
        /// </summary>
        public static string InviteTextPart2 {
            get {
                return ResourceManager.GetString("InviteTextPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بخند چون سپیتا انجام میده ....
        /// </summary>
        public static string InviteTextPart3 {
            get {
                return ResourceManager.GetString("InviteTextPart3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر گرامی با سپاس از انتخاب سپیتا .سفارش شما با کد.
        /// </summary>
        public static string Order_Post_Part1 {
            get {
                return ResourceManager.GetString("Order_Post_Part1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to با موفقیت ثبت گردید . با معرفی سپیتا به دوستانتون  از طریق نرم افزار و انجام اولین سفارش آن ها 5000 تومان اعتبار رایگان هدیه دریافت نمایید ..
        /// </summary>
        public static string Order_Post_Part2 {
            get {
                return ResourceManager.GetString("Order_Post_Part2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد فعال سازی:.
        /// </summary>
        public static string Registe_ActivationMessage_Part1 {
            get {
                return ResourceManager.GetString("Registe_ActivationMessage_Part1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر گرامی با وارد کردن کد بالا حساب کاربری شما فعال می گردد..
        /// </summary>
        public static string Registe_ActivationMessage_Part2 {
            get {
                return ResourceManager.GetString("Registe_ActivationMessage_Part2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  عزیز.
        /// </summary>
        public static string Registe_SuceessActivationMessage_Part1 {
            get {
                return ResourceManager.GetString("Registe_SuceessActivationMessage_Part1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت نام شما با موفقیت انجام شد. و اعتبار هدیه را دریافت کردید. هم اکنون می توانید اولین سفارش خود را ثبت نمایید.
        /// </summary>
        public static string Registe_SuceessActivationMessage_Part2 {
            get {
                return ResourceManager.GetString("Registe_SuceessActivationMessage_Part2", resourceCulture);
            }
        }
    }
}
